# Generated by Django 3.1.7 on 2021-03-09 00:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='NewsStories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('pol', 'politics'), ('art', 'art news'), ('tech', 'technology'), ('trivia', 'trivial news')], max_length=6)),
                ('region', models.CharField(choices=[('uk', 'United Kingdom news'), ('eu', 'European news'), ('w', 'World news')], max_length=2)),
                ('creation_date', models.DateField(default=datetime.date.today)),
                ('details', models.CharField(max_length=512)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_agency.author')),
            ],
        ),
    ]
