# Generated by Django 3.1.7 on 2021-03-09 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_agency', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsStories',
            new_name='NewsStory',
        ),
    ]
