# Generated by Django 3.1.7 on 2021-03-14 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news_agency', '0004_auto_20210314_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='author',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='author',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newsstory',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
