# Generated by Django 3.1.7 on 2021-03-14 18:24

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_agency', '0006_auto_20210314_1800'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='author',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
    ]
