# Generated by Django 3.1.7 on 2021-03-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_agency', '0008_auto_20210314_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(default='steve@gmail.com', max_length=254, null=True),
        ),
    ]
