# Generated by Django 3.1.7 on 2021-03-14 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_agency', '0011_auto_20210314_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='author',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='author',
            name='is_staff',
        ),
    ]
